# Setting
base-url: /B
about-url: https://dm-09.github.io/

# Main Page Setting
Header: 블로그
Description: 저의 블로그에 오신 것을 환영합니다. <br> 코딩 및 일상 등을 주제로 글을 씁니다.
more-btn-text: 글 더보기
recent-post: 최신 글

# Search
no-match-text: 해당 조건에 해당하는 글이 없습니다
